### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by heineiuo** [heineiuo/rippledb#1]
- [x] Support transaction #94
- [x] Support Database.destroy #114
- [x] Support reverse iterator #118
- [x] Support Database.repair #119

I prefer release at Jul 6, 2020, 1 year after totally rewritten.
